package com.mongo.example.mongodemo.models.apimodel;

public class VehicleControl {

	public enum Actions {
		TRUNK_CLOSE, TRUNK_OPEN, AC_ON, AC_OFF, ENGINE_OFF, ENGINE_ON, HAZARD_LIGHT_OFF, HAZARD_LIGHT_ON, 
		BONET_CLOSE, BONET_OPEN, AIROUTER_OFF, AIROUTER_ON, AIRCIRCULATION_INNER, AIRCIRCULATION_OUTER, 
		FLOWBOTH_ON, FLOWBOTH_OFF, FLOWUP_ON, FLOWUP_OFF, FLOWDOWN_OFF, FLOWDOWN_ON, 
		DEFROSTFRONT_OFF, DEFROSTFRONT_ON, DEFROSTREAR_OFF,DEFROSTREAR_ON,
		DOORFL_OFF, DOORFL_ON, DOORRR_ON, DOORRR_OFF, DOORFR_ON, DOORFR_OFF, DOORRL_ON, DOORRL_OFF,
		SLIDER_SET, ACTEMP_DECREASE, ACTEMP_INCREASE, HORN, HEADLIGHT_LOWER, HEADLIGHT_UPPER,
		HEADLIGHT_OFF, AC_VENT_FLOW_FRONT_BOTH, AC_VENT_FLOW_FRONT_UP,
		AC_VENT_FLOW_FRONT_DOWN, AC_VENT_FLOW_FRONT_OFF, AC_TEMPERATURE_FRONT, AC_TEMPERATURE_REAR,
		WINDOWMIRROR_FRONT_LEFT, AC_VENT_FLOW_REAR_UP, AC_VENT_FLOW_REAR_DOWN, AC_VENT_FLOW_REAR_BOTH, MASTER_LOCK_OPEN,
		MASTER_LOCK_CLOSE, CHILD_LOCK_CLOSE, CHILD_LOCK_OPEN, WINDOWMIRROR_REAR_LEFT, WINDOWMIRROR_REAR_RIGHT, WINDOWMIRROR_FRONT_RIGHT, SIDEMIRROR_LEFT, SIDEMIRROR_RIGHT, AC_VENT_FLOW_REAR_OFF, AC_STATE_REAR_ON, AC_STATE_REAR_OFF, AC_STATE_FRONT_ON, AC_STATE_FRONT_OFF
	}

	public VehicleControl() {
		super();
	}

}
